name: Daily Post to Telegram

on:
  schedule:
    # каждый день в 12:00 UTC — меняй на удобное тебе время
    - cron:  '0 12 * * *' 

jobs:
  post_daily:
    runs-on: ubuntu-latest
    steps:
      - name: HTTP POST to bot
        run: |
          curl -X POST https://dropify-bot.onrender.com/post_daily
